src/Entity/Book.php
<?php

namespace App\Entity;

use App\Repository\BookRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: BookRepository::class)]
class Book
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $title = null;

    #[ORM\Column(length: 255)]
    private ?string $year = null;

    #[ORM\Column(length: 255)]
    private ?string $isbn = null;

    #[ORM\Column]
    private ?int $list_count = null;

    #[ORM\Column(length: 255)]
    private ?string $icon_url = null;

    #[ORM\ManyToMany(targetEntity: Author::class, inversedBy: 'books')]

    private  $authors;

    public function __construct()
    {
        $this->authors = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getYear(): ?string
    {
        return $this->year;
    }

    public function setYear(string $year): self
    {
        $this->year = $year;
        return $this;
    }

    public function getIsbn(): ?string
    {
        return $this->isbn;
    }

    public function setIsbn(string $isbn): self
    {
        $this->isbn = $isbn;
        return $this;
    }

    public function getListCount(): ?int
    {
        return $this->list_count;
    }

    public function setListCount(int $list_count): self
    {
        $this->list_count = $list_count;
        return $this;
    }

    public function getIconUrl(): ?string
    {
        return $this->icon_url;
    }

    public function setIconUrl(string $icon_url): self
    {
        $this->icon_url = $icon_url;
        return $this;
    }

    public function addAuthor(Author $author): self
    {
        if (!$this->authors->contains($author)) {
            $this->authors[] = $author;
        }
        return $this;
    }

    public function removeAuthor(Author $author): self
    {
        $this->authors->removeElement($author);
        return $this;
    }

    public function getAuthors()
    {
        return $this->authors;
    }

}

src/Controller/BookController.php
<?php

namespace App\Controller;

use App\Entity\Author;
use App\Entity\Book;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Filesystem\Filesystem;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Validator\Validator\ValidatorInterface;

class BookController extends AbstractController
{
    protected $manager;

    public function __construct(ManagerRegistry $manager)
    {
       $this->manager = $manager;
    }

    #[Route('/book/list', name: 'book_list')]
    public function getBooks(): Response
    {
        $books = $this->repository(Book::class)->findAll();
        $authors = $this->repository(Author::class)->findAll();

        return $this->render('book/index.html.twig', [
            'title'    => 'Список книг',
            'books'     => $books,
            'authors'  => $authors,
        ]);
    }

    #[Route('/book/create', name: 'book_create')]
    public function create(Request $request, ValidatorInterface $validator)
    {
        $bookData = $request->request->all();
        $isValid = $this->isValidData($validator, $bookData);
        if(!$isValid['status']) {
            return $this->json($isValid);
        }

        $file = $request->files->get('icon_url');
        $bookData['icon_url'] = $this->saveFile($file);
        $response = $this->repository(Book::class)
                         ->create($bookData);
        return $this->json($response);
    }

    #[Route('/book/item/{id}', name: 'book_item')]
    public function getBook($id): Response
    {
        $book = $this->repository(Book::class)->find($id);
        $authors = $this->repository(Author::class)->findAll();

        return $this->render('book/item.html.twig', [
            'title'  => 'Книга',
            'book'   => $book,
            'authors'  => $authors
        ]);
    }

    #[Route('/book/update/{id}', name: 'book_update')]
    public function update($id, Request $request, ValidatorInterface $validator): Response
    {
        $bookData = $request->request->all();
        $isValid = $this->isValidData($validator, $bookData);
        if(!$isValid['status']) {
            return $this->json($isValid);
        }

        $hiddenIconUrl = (!empty($bookData['hidden_icon_url'])) ? $bookData['hidden_icon_url'] : '';
        $bookData['icon_url'] = $hiddenIconUrl;
        $file = $request->files->get('icon_url');
        if(!empty($file)) {
            $this->deleteFile($hiddenIconUrl);
            $bookData['icon_url'] = $this->saveFile($file);
        }
        $response = $this->repository(Book::class)
                         ->update($id, $bookData);
        return $this->json($response);
    }

    #[Route('/book/delete/{id}', name: 'book_delete')]
    public function delete($id, Filesystem $filesystem): Response
    {
        $iconUrl = $this->repository(Book::class)->delete($id);
        $this->deleteFile($iconUrl);
        return $this->redirectToRoute('book_list');
    }

    protected function saveFile($file = null) {
        $iconUrl = '';
        if (!empty($file)) {
            $originalFilename = pathinfo($file->getClientOriginalName(), PATHINFO_FILENAME);
            $newFilename = $originalFilename .'-' .uniqid(). '.jpg';
            try {
                $path = $this->getParameter('uploads_dir');
                $file->move($path, $newFilename);
                $iconUrl = $newFilename;
            } catch (FileException $e) {
                dump($e->getMessage()); die;
            }
        }
        return $iconUrl;
    }

    protected function deleteFile($iconUrl) {
        $status = false;
        $path = $this->getParameter('uploads_dir');
        $filePath = $path .'/'. $iconUrl;
        if(is_file($filePath) && file_exists($filePath)) {
            $status = unlink($filePath);
        }
        return $status;
    }

    protected function isValidData(ValidatorInterface $validator, $data) {

         $rules = [
             'title' => [new Assert\NotBlank, new Assert\Length(['min' => 2])],
             'year'  => [new Assert\notBlank],
             'isbn'  => [new Assert\notBlank],
             'list_count'  => [new Assert\notBlank],
         ];

         $constraints = new Assert\Collection($rules);

         $dataValidate = $errors = [];
         foreach ($rules as $name => $item) {
             if(isset($data[$name])) {
                 $dataValidate[$name] = $data[$name];
             }
         }

         $violations = $validator->validate($dataValidate, $constraints);

         $status = true;
         if (0 !== count($violations)) {
            $status = false;
            foreach ($violations as $violation) {
                $path = substr($violation->getPropertyPath(), 1, -1);
                $errors[$path] = $violation->getMessage();
            }
         }

         return [
             'status' => $status,
             'errors' => $errors,
         ];
    }

    protected function repository($class) {
        return $this->manager->getRepository($class);
    }
}

templates/book/form.html.twig
<!-- Modal -->
<div class="modal fade" id="bookModalFormContainer" tabindex="-1" aria-labelledby="exampleModalLabel"
     aria-hidden="true">
    <div class="modal-dialog">

        <form method="post" id="sendBookForm" enctype="multipart/form-data" >
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Добавить книгу</h5>
                    <button type="button" class="btn-close" data-mdb-dismiss="modal"
                            aria-label="Close"></button>
                </div>
                <div class="modal-body">

                    <div class="model-response-message" ></div>

                    <div class="form-outline">
                        <input type="text" id="title" value="" name="title" class="form-control"/>
                        <label class="form-label" for="title">Название</label>
                    </div>

                    <div class="form-outline" style="margin: 10px 0 10px 0">
                        <input type="text" id="year" value="" name="year" class="form-control"/>
                        <label class="form-label" for="year">Год</label>
                    </div>

                    <div class="form-outline" style="margin: 10px 0 10px 0">
                        <input type="text" id="isbn" value="" name="isbn" class="form-control"/>
                        <label class="form-label" for="isbn">ISBN</label>
                    </div>

                    <div class="form-outline" style="margin: 10px 0 10px 0">
                        <input type="text" id="list_count" value="" name="list_count"
                               class="form-control"/>
                        <label class="form-label" for="list_count">Кол / страниц</label>
                    </div>

                    <div class="form-outline" style="display: flex; margin: 10px 0 10px 0">
                        <label class="form-label" for="icon_url" style="width: 40%; padding-left: 10px">Иконка</label>
                        <input type="file" class="form-control" id="icon_url" value="" name="icon_url"
                               style="width: 60%; margin-left-left: auto"/>
                    </div>

                    <div class="form-outline select-wrapper" style="display: flex; " >
                        <label class="form-label select-label" style="width: 20%; padding-left: 10px" > Авторы </label>
                        <select class="select" name="authors_id[]" value="" multiple
                                style="width: 80%; height:250px; padding:5px; margin-left: auto; border-radius: 4px; border: 1px gainsboro solid">
                            <option value="">Выбрать авторов</option>
                            {% for item in authors %}
                                <option value="{{ item.id }}">{{ item.name }}  {{ item.surname }}</option>
                            {% endfor %}
                        </select>
                    </div>

                </div>

                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-mdb-dismiss="modal">Close</button>
                    <button onclick="createBook(event, '#sendBookForm')" type="submit" class="btn btn-primary">Сохранить</button>
                </div>

            </div>
        </form>

    </div>
</div>

templates/book/index.html.twig
{% extends 'base.html.twig' %}

{% block title %} {% endblock %}

{% block body %}

    <div class="container">

        <div style="display: flex; margin: 20px 0 20px 0;">

            <h5> {{ title }}</h5>


            <div style="margin-left: auto">

                <!-- Button trigger modal -->
                <button type="button" class="btn btn-primary" data-mdb-toggle="modal"
                        data-mdb-target="#bookModalFormContainer">
                        Добавить книгу
                </button>

                <div class="response-success-message" ></div>

                {% include 'book/form.html.twig' %}

            </div>
        </div>

        <table class="table align-middle mb-0 bg-white">
            <thead class="bg-light">
            <tr>
                <th>№</th>
                <th>Название</th>
                <th>Год</th>
                <th>ISBN</th>
                <th>Кол / страниц</th>
                <th>Show</th>
                <th>Delete</th>
            </tr>
            </thead>
            <tbody>

            {% for item in books %}
                <tr>
                    <td>
                        <div class="d-flex align-items-center">{{ item.id }}</div>
                    </td>
                    <td><p class="fw-normal mb-1">{{ item.title }}</p></td>
                    <td><p class="fw-normal mb-1">{{ item.year }}</p></td>
                    <td><p class="fw-normal mb-1">{{ item.isbn }}</p></td>
                    <td><p class="fw-normal mb-1">{{ item.listCount }}</p></td>
                    <td><a href="/book/item/{{ item.id }}">Посмотреть</a></td>
                    <td><a href="/book/delete/{{ item.id }}">Удалить</a></td>
                </tr>
            {% endfor %}

            </tbody>
        </table>

    </div>
{% endblock %}

templates/book/item.html.twig
{% extends 'base.html.twig' %}

{% block title %} {% endblock %}

{% block body %}

    <div class="container">

        <div style="display: flex; margin: 20px 0 20px 0;">

            <h5 style="font-style: italic"> {{ title }}: {{ book.title }}</h5>

            <div style="margin-left: auto">

                <!-- Button trigger modal -->
                <button type="button" class="btn btn-primary" data-mdb-toggle="modal"
                        data-mdb-target="#bookModalFormContainer">
                        Редактировать
                </button>

                <!-- Modal -->
                <div class="modal fade" id="bookModalFormContainer" tabindex="-1" aria-labelledby="exampleModalLabel"
                     aria-hidden="true">
                    <div class="modal-dialog">
                        <form action="/book/update/{{ book.id }}"
                              id="sendBookForm" method="post" enctype="multipart/form-data" >
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="exampleModalLabel">Добавить книгу</h5>
                                    <button type="button" class="btn-close" data-mdb-dismiss="modal"
                                            aria-label="Close"></button>
                                </div>
                                <div class="modal-body">

                                    <div class="form-outline">
                                        <input type="text" id="title" value="{{ book.title }}" name="title" class="form-control"/>
                                        <label class="form-label" for="title">Название</label>
                                    </div>

                                    <div class="form-outline" style="margin: 10px 0 10px 0">
                                        <input type="text" id="year" value="{{ book.year }}"  name="year" class="form-control"/>
                                        <label class="form-label" for="year">Год</label>
                                    </div>

                                    <div class="form-outline" style="margin: 10px 0 10px 0" >
                                        <input type="text" id="isbn" value="{{ book.isbn }}"  name="isbn" class="form-control"/>
                                        <label class="form-label" for="isbn">ISBN</label>
                                    </div>

                                    <div class="form-outline" style="margin: 10px 0 10px 0">
                                        <input type="text" id="list_count" value="{{ book.listCount }}"  name="list_count" class="form-control"/>
                                        <label class="form-label" for="list_count">Кол / страниц</label>
                                    </div>

                                    <input type="hidden"  value="{{ book.iconUrl }}" name="hidden_icon_url" />

                                    <div class="form-outline" style="display: flex; margin: 10px 0 10px 0">
                                        <label class="form-label" for="icon_url" style="width: 40%; padding-left: 10px">Иконка</label>
                                        <input type="file" class="form-control" id="icon_url" value="" name="icon_url"
                                               style="width: 60%; margin-left-left: auto"/>
                                    </div>

                                    <div class="form-outline select-wrapper" style="display: flex; " >
                                        <label class="form-label select-label" style="width: 20%; padding-left: 10px" > Авторы </label>
                                        <select class="select" name="authors_id[]" value="" multiple
                                                style="width: 80%; height:250px; padding:5px; margin-left: auto; border-radius: 4px; border: 1px gainsboro solid">
                                                <option value="">Выбрать авторов</option>
                                                {% for item in authors %}
                                                    <option value="{{ item.id }}">{{ item.name }}  {{ item.surname }}</option>
                                                {% endfor %}
                                        </select>
                                    </div>

                                </div>

                                <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-mdb-dismiss="modal">Close</button>
                                    <button onclick="updateBook(event, '#sendBookForm', {{ book.id }})" type="submit" class="btn btn-primary">Сохранить</button>
                                </div>

                            </div>
                        </form>
                    </div>
                </div>

            </div>

        </div>

        <div class="card" >
            <div class="card-body" style="display: flex">
                <div>
                    <img src="/uploads/{{ book.iconUrl }}" class="card-img-top" alt=""
                         style="width: 200px; border-radius: 0px; margin-bottom: 20px"/>
                    <h5 class="card-title"> {{ book.title }}</h5>
                    <p class="card-text"> Год: {{ book.year }}</p>
                    <p class="card-text"> ISBN: {{ book.isbn }}</p>
                    <p class="card-text"> Кол / страниц: {{ book.listCount }}</p>
                </div>
                <div style="margin-left: 40px; padding-left: 40px; border-left: 1px gainsboro solid">
                    <h5 class="card-title"> Авторы </h5>
                    <ul>
                        {% for item in book.authors %}
                          <li> {{ item.name }} {{ item.surname }}</li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>

    </div>

{% endblock %}